[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cansat"
authors = [{name = "Tessa Nikander", email = "tessa@kitsat.fi"}]
dynamic = ["version", "description"]
